### ISSUE TITLE
LNURLp webhook stops working after a while (RaspiBlitz)

### ISSUE THREAD

**Issue by Fittiboy** [lnbits/lnbits#200]
I have a few LNURLp links which are supposed to dispatch webhook requests. Initially this works without issue, but after a few hours of running LNbits, no request ever reaches my webhook server (running on the same local network). 
On success, the response code shows up:
![image](https://user-images.githubusercontent.com/28876473/120972028-99c32d80-c76d-11eb-8dd2-71526075d012.png)
But after runnig for a while, LNbits doesn't even seem to _try_ to dispatch the webhook request:
![image](https://user-images.githubusercontent.com/28876473/120972293-e149b980-c76d-11eb-88c9-7f20308ee265.png)
The server handling the webhooks is running entirely without issue during this.
Restarting LNbits always fixes this. I've tried sending 10 payments without restarting, and none of them triggered the webhook. After restarting, payments triggered it again.

**Comment by fiatjaf** [comment]
What is the LNbits version/commit? Can you upgrade to the latest `master`? What do the logs show? We had some nursery problems (stuff related to the async listeners for incoming payments) in the past but they seem to have been _mostly_ fixed by now.

**Comment by Fittiboy** [comment]
I've now (after creating a backup) checked out master, `git pull`ed, and restarted LNbits. I'm assuming that is all that needed to be done?
Previous version was the latest `raspiblitz` [tag](https://github.com/lnbits/lnbits/tree/raspiblitz), so [this commit](https://github.com/lnbits/lnbits/commit/bcecf6d43111199302d9f7152ecb7e7a4735662a).

**Comment by fiatjaf** [comment]
Yes, that's what is needed.

**Comment by Fittiboy** [comment]
Sadly, the issue persists. I got two donations during today's stream, but only the first one ever reached my webhook. Both confirmed as settled by my node, as well as LNbits itself. But the second one didn't get sent to the webhook. Interestingly enough, not even the first transaction has the `wh_status: 200` included, even though my server did respond with that.

**Comment by Fittiboy** [comment]
Just found something very interesting in the logs. This is from a payment that didn't make it to the webhook:
```Jun 11 06:31:30 raspberrypi sh[11854]: [2021-06-11 06:31:30 +0100] [11855] [ERROR] ASGI Framework Lifespan error, continuing without Lifespan support
Jun 11 06:31:30 raspberrypi sh[11854]: Traceback (most recent call last):
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jun 11 06:31:30 raspberrypi sh[11854]:     cursor, statement, parameters, context
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Jun 11 06:31:30 raspberrypi sh[11854]:     cursor.execute(statement, parameters)
Jun 11 06:31:30 raspberrypi sh[11854]: sqlite3.OperationalError: no such table: targets
Jun 11 06:31:30 raspberrypi sh[11854]: The above exception was the direct cause of the following exception:
Jun 11 06:31:30 raspberrypi sh[11854]: Traceback (most recent call last):
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/hypercorn/trio/lifespan.py", line 29, in handle_lifespan
Jun 11 06:31:30 raspberrypi sh[11854]:     await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
Jun 11 06:31:30 raspberrypi sh[11854]:     await app(scope, receive, send)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 2117, in __call__
Jun 11 06:31:30 raspberrypi sh[11854]:     await self.asgi_app(scope, receive, send)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 2140, in asgi_app
Jun 11 06:31:30 raspberrypi sh[11854]:     await asgi_handler(receive, send)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/asgi.py", line 115, in __call__
Jun 11 06:31:30 raspberrypi sh[11854]:     break
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 741, in __aexit__
Jun 11 06:31:30 raspberrypi sh[11854]:     raise combined_error_from_nursery
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/extensions/splitpayments/tasks.py", line 16, in register_listeners
Jun 11 06:31:30 raspberrypi sh[11854]:     await wait_for_paid_invoices(invoice_paid_chan_recv)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/extensions/splitpayments/tasks.py", line 21, in wait_for_paid_invoices
Jun 11 06:31:30 raspberrypi sh[11854]:     await on_invoice_paid(payment)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/extensions/splitpayments/tasks.py", line 30, in on_invoice_paid
Jun 11 06:31:30 raspberrypi sh[11854]:     targets = await get_targets(payment.wallet_id)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/extensions/splitpayments/crud.py", line 8, in get_targets
Jun 11 06:31:30 raspberrypi sh[11854]:     rows = await db.fetchall("SELECT * FROM targets WHERE source = ?", (source_wallet,))
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/db.py", line 48, in fetchall
Jun 11 06:31:30 raspberrypi sh[11854]:     result = await conn.execute(query, values)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/lnbits/db.py", line 26, in execute
Jun 11 06:31:30 raspberrypi sh[11854]:     return await self.conn.execute(query, values)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy_aio/base.py", line 288, in execute
Jun 11 06:31:30 raspberrypi sh[11854]:     self._connection.execute, *args, **kwargs)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy_aio/base.py", line 230, in _run_in_thread
Jun 11 06:31:30 raspberrypi sh[11854]:     return await _self._worker.run(_func, args, kwargs)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy_aio/trio.py", line 70, in run
Jun 11 06:31:30 raspberrypi sh[11854]:     return resp.unwrap()
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/outcome/_impl.py", line 138, in unwrap
Jun 11 06:31:30 raspberrypi sh[11854]:     raise captured_error
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
Jun 11 06:31:30 raspberrypi sh[11854]:     return self._execute_text(object_, multiparams, params)
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
Jun 11 06:31:30 raspberrypi sh[11854]:     parameters,
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
Jun 11 06:31:30 raspberrypi sh[11854]:     e, statement, parameters, cursor, context
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
Jun 11 06:31:30 raspberrypi sh[11854]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Jun 11 06:31:30 raspberrypi sh[11854]:     raise exception
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Jun 11 06:31:30 raspberrypi sh[11854]:     cursor, statement, parameters, context
Jun 11 06:31:30 raspberrypi sh[11854]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Jun 11 06:31:30 raspberrypi sh[11854]:     cursor.execute(statement, parameters)
Jun 11 06:31:30 raspberrypi sh[11854]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: targets
Jun 11 06:31:30 raspberrypi sh[11854]: [SQL: SELECT * FROM targets WHERE source = ?]
```

**Comment by fiatjaf** [comment]
Hmm, sorry, this is a different issue caused by the fact that I forgot to tell you to rerun the database migrations after the update.

The fact that this error has occurred means the asynchronous listener was working though.

Running the migrations should fix it. Should be something like https://github.com/rootzoll/raspiblitz/blob/fc1d44104bc22d85ebebd7b0d6ee2240722a9edf/home.admin/config.scripts/bonus.lnbits.sh#L302.

**Comment by Fittiboy** [comment]
I actually ran migrations immediately afterwards, and haven't had any issues since then!

**Comment by fiatjaf** [comment]
Great to hear! Let's close and please reopen if you have more issues. Or join https://t.me/lnbits to complain.
