### ISSUE TITLE
[BUG] Local time for invoices shown incorrectly and error shown

### ISSUE THREAD

**Issue by jjim1982** [lnbits/lnbits#3103]
The local time for invoices seems to be displayed incorrectly. The UTC time shown in the popup is correct, but the one above that says 9 hours ago when it should be a few seconds ago. It seems to be treating the UTC time as my local time.

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/441ae4b9-ff83-4b0d-b485-465071ba6de6" />

I also get the error "**_can't compare offset-naive and offset-aware datetimes 500_**" for one of my wallets. However the incorrect time is shown in all wallets.

- LNbits version: 1
- Database postgres

Log:

`Apr 11 04:35:41 vps poetry[131837]:   + Exception Group Traceback (most recent call last):
Apr 11 04:35:41 vps poetry[131837]:   |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:   |     yield
Apr 11 04:35:41 vps poetry[131837]:   |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 186, in __call__
Apr 11 04:35:41 vps poetry[131837]:   |     async with anyio.create_task_group() as task_group:
Apr 11 04:35:41 vps poetry[131837]:   |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
Apr 11 04:35:41 vps poetry[131837]:   |     raise BaseExceptionGroup(
Apr 11 04:35:41 vps poetry[131837]:   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
Apr 11 04:35:41 vps poetry[131837]:   +-+---------------- 1 ----------------
Apr 11 04:35:41 vps poetry[131837]:     | Traceback (most recent call last):
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, _send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:     |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     |     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/slowapi/middleware.py", line 136, in dispatch
Apr 11 04:35:41 vps poetry[131837]:     |     response = await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     |     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:     |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     |     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 236, in block_allow_ip_middleware
Apr 11 04:35:41 vps poetry[131837]:     |     return await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     |     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:     |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     |     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 249, in first_install_middleware
Apr 11 04:35:41 vps poetry[131837]:     |     return await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     |     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 117, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 61, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/sessions.py", line 85, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, send_wrapper)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:     |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     |     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 133, in dispatch
Apr 11 04:35:41 vps poetry[131837]:     |     response = await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     |     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 20, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await responder(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 39, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, self.send_with_gzip)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     |     await app(scope, receive, sender)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
Apr 11 04:35:41 vps poetry[131837]:     |     await self.middleware_stack(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
Apr 11 04:35:41 vps poetry[131837]:     |     await route.handle(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
Apr 11 04:35:41 vps poetry[131837]:     |     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
Apr 11 04:35:41 vps poetry[131837]:     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     |     raise exc
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     |     await app(scope, receive, sender)
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
Apr 11 04:35:41 vps poetry[131837]:     |     response = await f(request)
Apr 11 04:35:41 vps poetry[131837]:     |                ^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
Apr 11 04:35:41 vps poetry[131837]:     |     raw_response = await run_endpoint_function(
Apr 11 04:35:41 vps poetry[131837]:     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
Apr 11 04:35:41 vps poetry[131837]:     |     return await dependant.call(**values)
Apr 11 04:35:41 vps poetry[131837]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/core/views/payment_api.py", line 171, in api_payments_daily_stats
Apr 11 04:35:41 vps poetry[131837]:     |     return await get_payments_daily_stats(filters)
Apr 11 04:35:41 vps poetry[131837]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     |   File "/home/ubuntu/lnbits/lnbits/core/services/payments.py", line 412, in get_payments_daily_stats
Apr 11 04:35:41 vps poetry[131837]:     |     start_date = min(data_in[0].date, data_out[0].date)
Apr 11 04:35:41 vps poetry[131837]:     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:     | TypeError: can't compare offset-naive and offset-aware datetimes
Apr 11 04:35:41 vps poetry[131837]:     +------------------------------------
Apr 11 04:35:41 vps poetry[131837]: During handling of the above exception, another exception occurred:
Apr 11 04:35:41 vps poetry[131837]: Traceback (most recent call last):
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, _send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/slowapi/middleware.py", line 136, in dispatch
Apr 11 04:35:41 vps poetry[131837]:     response = await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 236, in block_allow_ip_middleware
Apr 11 04:35:41 vps poetry[131837]:     return await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 249, in first_install_middleware
Apr 11 04:35:41 vps poetry[131837]:     return await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 117, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 61, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/sessions.py", line 85, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, send_wrapper)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 185, in __call__
Apr 11 04:35:41 vps poetry[131837]:     with collapse_excgroups():
Apr 11 04:35:41 vps poetry[131837]:   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
Apr 11 04:35:41 vps poetry[131837]:     self.gen.throw(value)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 187, in __call__
Apr 11 04:35:41 vps poetry[131837]:     response = await self.dispatch_func(request, call_next)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/middleware.py", line 133, in dispatch
Apr 11 04:35:41 vps poetry[131837]:     response = await call_next(request)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 163, in call_next
Apr 11 04:35:41 vps poetry[131837]:     raise app_exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/base.py", line 149, in coro
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive_or_disconnect, send_no_error)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 20, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await responder(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 39, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, self.send_with_gzip)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     await app(scope, receive, sender)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
Apr 11 04:35:41 vps poetry[131837]:     await self.middleware_stack(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
Apr 11 04:35:41 vps poetry[131837]:     await route.handle(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
Apr 11 04:35:41 vps poetry[131837]:     await self.app(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
Apr 11 04:35:41 vps poetry[131837]:     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     raise exc
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
Apr 11 04:35:41 vps poetry[131837]:     await app(scope, receive, sender)
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
Apr 11 04:35:41 vps poetry[131837]:     response = await f(request)
Apr 11 04:35:41 vps poetry[131837]:                ^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
Apr 11 04:35:41 vps poetry[131837]:     raw_response = await run_endpoint_function(
Apr 11 04:35:41 vps poetry[131837]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/.cache/pypoetry/virtualenvs/lnbits-FjepO-aV-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
Apr 11 04:35:41 vps poetry[131837]:     return await dependant.call(**values)
Apr 11 04:35:41 vps poetry[131837]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/core/views/payment_api.py", line 171, in api_payments_daily_stats
Apr 11 04:35:41 vps poetry[131837]:     return await get_payments_daily_stats(filters)
Apr 11 04:35:41 vps poetry[131837]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]:   File "/home/ubuntu/lnbits/lnbits/core/services/payments.py", line 412, in get_payments_daily_stats
Apr 11 04:35:41 vps poetry[131837]:     start_date = min(data_in[0].date, data_out[0].date)
Apr 11 04:35:41 vps poetry[131837]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 11 04:35:41 vps poetry[131837]: TypeError: can't compare offset-naive and offset-aware datetimes
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.07 | ERROR | Exception: can't compare offset-naive and offset-aware datetimes
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.07 | INFO | 118.17.227.115:0 - "GET /api/v1/payments/stats/daily?wallet_id=2r2r HTTP/1.1" 500
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.07 | ERROR | Exception in ASGI application
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.10 | INFO | 118.17.227.115:0 - "GET /api/v1/payments/paginated?limit=10&offset=0&sortby=time&direction=desc&status%5Bne%5D=failed HTTP/1.1" 200
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.19 | INFO | 118.17.227.115:0 - "GET /api/v1/extension HTTP/1.1" 200
Apr 11 04:35:41 vps poetry[131837]: 2025-04-11 04:35:41.30 | INFO | 118.17.227.115:0 - "GET /api/v1/payments/paginated?limit=10&offset=0&sortby=time&direction=desc&status%5Bne%5D=failed HTTP/1.1" 200`

**Comment by motorina0** [comment]
- `can't compare offset-naive and offset-aware datetimes` error fixed here: https://github.com/lnbits/lnbits/pull/3104

**Comment by jjim1982** [comment]
It seems this is not fixed in 1.1. There's no change to dates being shown as 9 hours behind what they should be. And I just noticed it prevents invoices from being paid (probably as they are seen as already expired).

**Comment by motorina0** [comment]
> dates being shown as 9 hours behind what they should be (my timezone is GMT+9).

Are you running a SQLite on the same machine (or a machine with the same timezone)?
That is an issue I've noticed, but I do not have a fix for it (SQLite behavior).

> And I just noticed it prevents invoices from being paid

what error do you get here?

**Comment by jjim1982** [comment]
postgres on same machine. no error, just sits pending (I assume because the expired time has passed already?)

**Comment by jeremyd** [comment]
I'm still seeing this time problem, lnbits 1.2.0-rc2.  all my invoices are displaying UTC time as localtime. 🤔 Is this because I'm running in a container?

**Comment by motorina0** [comment]
> I'm still seeing this time problem, lnbits 1.2.0-rc2. all my invoices are displaying UTC time as localtime. 🤔 Is this because I'm running in a container?

Retested on demo and saas instance (docker container), looks to work fine.
Can you please hard-refresh your browser or try in an incognito windows.
